<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class MusicaArtista extends \Application\Entity\MusicaArtista implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Application\\Entity\\MusicaArtista' . "\0" . 'cdMusicaArtista', '' . "\0" . 'Application\\Entity\\MusicaArtista' . "\0" . 'artista', '' . "\0" . 'Application\\Entity\\MusicaArtista' . "\0" . 'musica', '' . "\0" . 'Application\\Entity\\MusicaArtista' . "\0" . 'genero', '' . "\0" . 'Application\\Entity\\MusicaArtista' . "\0" . 'stLinkVideo', '' . "\0" . 'Application\\Entity\\MusicaArtista' . "\0" . 'stLinkCifra', '' . "\0" . 'Application\\Entity\\MusicaArtista' . "\0" . 'stTempoDuracao', '' . "\0" . 'Application\\Entity\\MusicaArtista' . "\0" . 'stTom');
        }

        return array('__isInitialized__', '' . "\0" . 'Application\\Entity\\MusicaArtista' . "\0" . 'cdMusicaArtista', '' . "\0" . 'Application\\Entity\\MusicaArtista' . "\0" . 'artista', '' . "\0" . 'Application\\Entity\\MusicaArtista' . "\0" . 'musica', '' . "\0" . 'Application\\Entity\\MusicaArtista' . "\0" . 'genero', '' . "\0" . 'Application\\Entity\\MusicaArtista' . "\0" . 'stLinkVideo', '' . "\0" . 'Application\\Entity\\MusicaArtista' . "\0" . 'stLinkCifra', '' . "\0" . 'Application\\Entity\\MusicaArtista' . "\0" . 'stTempoDuracao', '' . "\0" . 'Application\\Entity\\MusicaArtista' . "\0" . 'stTom');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (MusicaArtista $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getCdMusicaArtista()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getCdMusicaArtista();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCdMusicaArtista', array());

        return parent::getCdMusicaArtista();
    }

    /**
     * {@inheritDoc}
     */
    public function getArtista()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArtista', array());

        return parent::getArtista();
    }

    /**
     * {@inheritDoc}
     */
    public function getMusica()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMusica', array());

        return parent::getMusica();
    }

    /**
     * {@inheritDoc}
     */
    public function getGenero()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGenero', array());

        return parent::getGenero();
    }

    /**
     * {@inheritDoc}
     */
    public function getStLinkVideo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStLinkVideo', array());

        return parent::getStLinkVideo();
    }

    /**
     * {@inheritDoc}
     */
    public function getStLinkCifra()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStLinkCifra', array());

        return parent::getStLinkCifra();
    }

    /**
     * {@inheritDoc}
     */
    public function getStTempoDuracao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStTempoDuracao', array());

        return parent::getStTempoDuracao();
    }

    /**
     * {@inheritDoc}
     */
    public function getStTom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStTom', array());

        return parent::getStTom();
    }

    /**
     * {@inheritDoc}
     */
    public function setCdMusicaArtista($cdMusicaArtista)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCdMusicaArtista', array($cdMusicaArtista));

        return parent::setCdMusicaArtista($cdMusicaArtista);
    }

    /**
     * {@inheritDoc}
     */
    public function setArtista(\Application\Entity\Artista $artista)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArtista', array($artista));

        return parent::setArtista($artista);
    }

    /**
     * {@inheritDoc}
     */
    public function setMusica(\Application\Entity\Musica $musica)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMusica', array($musica));

        return parent::setMusica($musica);
    }

    /**
     * {@inheritDoc}
     */
    public function setGenero(\Application\Entity\Genero $genero)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGenero', array($genero));

        return parent::setGenero($genero);
    }

    /**
     * {@inheritDoc}
     */
    public function setStLinkVideo($stLinkVideo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStLinkVideo', array($stLinkVideo));

        return parent::setStLinkVideo($stLinkVideo);
    }

    /**
     * {@inheritDoc}
     */
    public function setStLinkCifra($stLinkCifra)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStLinkCifra', array($stLinkCifra));

        return parent::setStLinkCifra($stLinkCifra);
    }

    /**
     * {@inheritDoc}
     */
    public function setStTempoDuracao($stTempoDuracao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStTempoDuracao', array($stTempoDuracao));

        return parent::setStTempoDuracao($stTempoDuracao);
    }

    /**
     * {@inheritDoc}
     */
    public function setStTom($stTom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStTom', array($stTom));

        return parent::setStTom($stTom);
    }

}
