<?php echo $this->doctype(); ?>
<html lang="en" ng-app="myApp">
    <head>
        <meta charset="utf-8">
        <title>Setlist</title>
        <link href="/css/bootstrap.css" media="screen" rel="stylesheet" type="text/css">
        <link href="/css/style.css" rel="stylesheet" type="text/css">
        <link href="/css/ui.css" media="screen" rel="stylesheet" type="text/css">
    </head>
    <body>
        <!-- Static navbar -->
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">
                    <a class="navbar-brand" href="/#/">Setlist</a>
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="/#/musica">Músicas</a></li>
                        <!--<li><a href="/#/produtos">Produtos</a></li>-->
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
    <ui-preloader ng-show="loading"></ui-preloader>
    <div ng-hide="loading">
        <?php echo $this->content; ?>
    </div>
    <script src="/js/angular.min.js"></script>
    <script src="/js/angular-route.min.js"></script>
    <script src="/js/angular-resource.min.js"></script>
    <script src="/js/geral.js"></script>
    <script src="/projetoangular/app.js"></script>
    <script src="/projetoangular/controllers/musicaController.js"></script>
    <script src="/projetoangular/controllers/setlistController.js"></script>
    <script src="/projetoangular/services/artistaService.js"></script>
    <script src="/projetoangular/services/musicaService.js"></script>
    <script src="/projetoangular/services/generoService.js"></script>
    <script src="/projetoangular/services/setlistService.js"></script>
    <script src="/projetoangular/directives/uiPreloaderDirective.js"></script>
    <script src="/projetoangular/config/interceptorsConfig.js"></script>
    <script src="/projetoangular/interceptors/loadingInterceptor.js"></script>
</body>
</html>
